### Track Page View
POST http://localhost:80/track
Content-Type: application/json

{
  "page_id": "home",
  "user_id": "user123"
}

### Retrieve Stats
GET http://localhost:80/stats
Content-Type: application/json

###
